### PR TITLE
Upgrade to Ember-CLI 0.0.42

### PR DESCRIPTION
**Pull request by broerse**

### CODE REVIEW

**Comment by sehnpaa** [comment]
Hi @broerse! I have received a notification about this PR one hour ago, but the PR seem to be a couple of years old. Do you have any idea what's going on?

**Comment by broerse** [comment]
Hi @sehnpaa I don't know. It seems like a bug from github with my the forgotten PR https://github.com/balupton/ember-cli-blog/pull/7
I will remove it just to be sure.

Thanks

- Martin

**Comment by broerse** [comment]
Perhaps it is the houndci-bot thing. Perhaps the original author uses houndci-bot ?

**Comment by sehnpaa** [comment]
Thanks. That is weird, but okay. No problem. I'll just close this one together with https://github.com/sehnpaa/ember-cli-blog/pull/2.

Oh, and thanks for your previous work, @broerse! Have a good one!

**Pull request closed without merging**
